### ISSUE TITLE
#FeatureRequest Give user ability to animate only new items in the list. 

### ISSUE THREAD

**Issue by TheSomeshKumar** [theonlyanil/Rebound-RecyclerView-Android#1]
Material design guideline suggests to animate only new items in `ViewGroup` so I think there should be an option to turn off the animation on previously visible rows.

**Comment by theonlyanil** [comment]
Hi Somesh. I will add this feature soon. Meanwhile can you link me to the page which has the guidelines to animate only new items in ViewGroup?

**Comment by someshkumar049** [comment]
@theonlyanil [https://material.io/design/motion/customization.html#sequencing](url) 

> Caution.
Avoid stagger for frequent interactions. Repetition can dull the impact and create distraction when the same effect is seen many times in succession.

Previously, In material design 1.0 it was written more directly.

**Comment by TheSomeshKumar** [comment]
@theonlyanil [Motion > Sequencing > Stagger  ](https://material.io/design/motion/customization.html#sequencing) 

> Caution.
Avoid stagger for frequent interactions. Repetition can dull the impact and create distraction when the same effect is seen many times in succession.

Previously, In material design 1.0 it was written more directly.

**Comment by theonlyanil** [comment]
Found this:

> Stagger hints that member of a group may act as a separate affordance. This staggered movement encourages interaction with individual cards.

**Comment by theonlyanil** [comment]
Done. Please check the latest release.

**Comment by TheSomeshKumar** [comment]
Okay good but why are you using init method for this ? Users will have hard time understanding the `true ` `false `flag in init method. Have you seen my proposed PL ?

**Comment by theonlyanil** [comment]
Alright. I got your point. Will update the lib soon.
